name: Test
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  # Perhaps this should be updated for other branches 
  push:
    branches:
      - master
      - runModules
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 
      - name: Test with pytest
        run: pytest -vv
